'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WebApplication1

    Partial Public Class Departamentos
        Public Property IdDepartamento As Integer
        Public Property DescripcionDepartamento As String
    
        Public Overridable Property Municipios As ICollection(Of Municipios) = New HashSet(Of Municipios)
    
    End Class

End Namespace
