'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace WebApplication1

    Partial Public Class DiegoLopezEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=DiegoLopezEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property Departamentos() As DbSet(Of Departamentos)
        Public Overridable Property Municipios() As DbSet(Of Municipios)
        Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    
    End Class

End Namespace
