'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WebApplication1

    Partial Public Class Municipios
        Public Property IdMunicipio As Integer
        Public Property DescripcionMunicipio As String
        Public Property IdDepartamento As Integer
    
        Public Overridable Property Departamentos As Departamentos
    
    End Class

End Namespace
