//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiegoLopez.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjConsuta", Namespace="http://schemas.datacontract.org/2004/07/WebApplication2")]
    [System.SerializableAttribute()]
    public partial class ObjConsuta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDeptoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMunicipioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreDeptoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreMunicipioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDepto {
            get {
                return this.IdDeptoField;
            }
            set {
                if ((this.IdDeptoField.Equals(value) != true)) {
                    this.IdDeptoField = value;
                    this.RaisePropertyChanged("IdDepto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMunicipio {
            get {
                return this.IdMunicipioField;
            }
            set {
                if ((this.IdMunicipioField.Equals(value) != true)) {
                    this.IdMunicipioField = value;
                    this.RaisePropertyChanged("IdMunicipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreDepto {
            get {
                return this.NombreDeptoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreDeptoField, value) != true)) {
                    this.NombreDeptoField = value;
                    this.RaisePropertyChanged("NombreDepto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreMunicipio {
            get {
                return this.NombreMunicipioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreMunicipioField, value) != true)) {
                    this.NombreMunicipioField = value;
                    this.RaisePropertyChanged("NombreMunicipio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        DiegoLopez.ServiceReference1.ObjConsuta[] GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        System.Threading.Tasks.Task<DiegoLopez.ServiceReference1.ObjConsuta[]> GetDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : DiegoLopez.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<DiegoLopez.ServiceReference1.IService>, DiegoLopez.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DiegoLopez.ServiceReference1.ObjConsuta[] GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<DiegoLopez.ServiceReference1.ObjConsuta[]> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
    }
}
